package com.timecaps.dao.entity;

public class RecordWithBLOBs extends Record {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.urls
     *
     * @mbggenerated
     */
    private String urls;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.title
     *
     * @return the value of record.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.title
     *
     * @param title the value for record.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.content
     *
     * @return the value of record.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.content
     *
     * @param content the value for record.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.urls
     *
     * @return the value of record.urls
     *
     * @mbggenerated
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.urls
     *
     * @param urls the value for record.urls
     *
     * @mbggenerated
     */
    public void setUrls(String urls) {
        this.urls = urls == null ? null : urls.trim();
    }
}